-- A股财务数据表（自动生成，基于 xtquant 返回的 DataFrame 结构）
-- 8张表：三大报表 + 每股指标 + 股本 + 股东户数 + 十大股东/流通股东
-- 报表类表(Balance/Income/CashFlow/Pershareindex)主键含 announce_date，保留修订历史

-- Balance → fin_balance
CREATE TABLE IF NOT EXISTS "fin_balance" (
    "internal_shoule_recv" DOUBLE PRECISION,
    "fixed_capital_clearance" DOUBLE PRECISION,
    "should_pay_money" DOUBLE PRECISION,
    "settlement_payment" DOUBLE PRECISION,
    "receivable_premium" DOUBLE PRECISION,
    "accounts_receivable_reinsurance" DOUBLE PRECISION,
    "reinsurance_contract_reserve" DOUBLE PRECISION,
    "dividends_payable" DOUBLE PRECISION,
    "tax_rebate_for_export" DOUBLE PRECISION,
    "subsidies_receivable" DOUBLE PRECISION,
    "deposit_receivable" DOUBLE PRECISION,
    "apportioned_cost" DOUBLE PRECISION,
    "profit_and_current_assets_with_deal" DOUBLE PRECISION,
    "current_assets_one_year" DOUBLE PRECISION,
    "long_term_receivables" DOUBLE PRECISION,
    "other_long_term_investments" DOUBLE PRECISION,
    "original_value_of_fixed_assets" DOUBLE PRECISION,
    "net_value_of_fixed_assets" DOUBLE PRECISION,
    "depreciation_reserves_of_fixed_assets" DOUBLE PRECISION,
    "productive_biological_assets" DOUBLE PRECISION,
    "public_welfare_biological_assets" DOUBLE PRECISION,
    "oil_and_gas_assets" DOUBLE PRECISION,
    "development_expenditure" DOUBLE PRECISION,
    "right_of_split_share_distribution" DOUBLE PRECISION,
    "other_non_mobile_assets" DOUBLE PRECISION,
    "handling_fee_and_commission" DOUBLE PRECISION,
    "other_payables" DOUBLE PRECISION,
    "margin_payable" DOUBLE PRECISION,
    "internal_accounts_payable" DOUBLE PRECISION,
    "advance_cost" DOUBLE PRECISION,
    "insurance_contract_reserve" DOUBLE PRECISION,
    "broker_buying_and_selling_securities" DOUBLE PRECISION,
    "acting_underwriting_securities" DOUBLE PRECISION,
    "international_ticket_settlement" DOUBLE PRECISION,
    "domestic_ticket_settlement" DOUBLE PRECISION,
    "deferred_income" DOUBLE PRECISION,
    "short_term_bonds_payable" DOUBLE PRECISION,
    "long_term_deferred_income" DOUBLE PRECISION,
    "undetermined_investment_losses" DOUBLE PRECISION,
    "quasi_distribution_of_cash_dividends" DOUBLE PRECISION,
    "provisions_not" DOUBLE PRECISION,
    "cust_bank_dep" DOUBLE PRECISION,
    "provisions" DOUBLE PRECISION,
    "less_tsy_stk" DOUBLE PRECISION,
    "cash_equivalents" DOUBLE PRECISION,
    "loans_to_oth_banks" DOUBLE PRECISION,
    "tradable_fin_assets" DOUBLE PRECISION,
    "derivative_fin_assets" DOUBLE PRECISION,
    "bill_receivable" DOUBLE PRECISION,
    "account_receivable" DOUBLE PRECISION,
    "advance_payment" DOUBLE PRECISION,
    "int_rcv" DOUBLE PRECISION,
    "other_receivable" DOUBLE PRECISION,
    "red_monetary_cap_for_sale" DOUBLE PRECISION,
    "agency_bus_assets" DOUBLE PRECISION,
    "inventories" DOUBLE PRECISION,
    "other_current_assets" DOUBLE PRECISION,
    "total_current_assets" DOUBLE PRECISION,
    "loans_and_adv_granted" DOUBLE PRECISION,
    "fin_assets_avail_for_sale" DOUBLE PRECISION,
    "held_to_mty_invest" DOUBLE PRECISION,
    "long_term_eqy_invest" DOUBLE PRECISION,
    "invest_real_estate" DOUBLE PRECISION,
    "accumulated_depreciation" DOUBLE PRECISION,
    "fix_assets" DOUBLE PRECISION,
    "constru_in_process" DOUBLE PRECISION,
    "construction_materials" DOUBLE PRECISION,
    "long_term_liabilities" DOUBLE PRECISION,
    "intang_assets" DOUBLE PRECISION,
    "goodwill" DOUBLE PRECISION,
    "long_deferred_expense" DOUBLE PRECISION,
    "deferred_tax_assets" DOUBLE PRECISION,
    "total_non_current_assets" DOUBLE PRECISION,
    "tot_assets" DOUBLE PRECISION,
    "shortterm_loan" DOUBLE PRECISION,
    "borrow_central_bank" DOUBLE PRECISION,
    "loans_oth_banks" DOUBLE PRECISION,
    "tradable_fin_liab" DOUBLE PRECISION,
    "derivative_fin_liab" DOUBLE PRECISION,
    "notes_payable" DOUBLE PRECISION,
    "accounts_payable" DOUBLE PRECISION,
    "advance_peceipts" DOUBLE PRECISION,
    "fund_sales_fin_assets_rp" DOUBLE PRECISION,
    "empl_ben_payable" DOUBLE PRECISION,
    "taxes_surcharges_payable" DOUBLE PRECISION,
    "int_payable" DOUBLE PRECISION,
    "dividend_payable" DOUBLE PRECISION,
    "other_payable" DOUBLE PRECISION,
    "non_current_liability_in_one_year" DOUBLE PRECISION,
    "other_current_liability" DOUBLE PRECISION,
    "total_current_liability" DOUBLE PRECISION,
    "long_term_loans" DOUBLE PRECISION,
    "bonds_payable" DOUBLE PRECISION,
    "longterm_account_payable" DOUBLE PRECISION,
    "grants_received" DOUBLE PRECISION,
    "deferred_tax_liab" DOUBLE PRECISION,
    "other_non_current_liabilities" DOUBLE PRECISION,
    "non_current_liabilities" DOUBLE PRECISION,
    "tot_liab" DOUBLE PRECISION,
    "cap_stk" DOUBLE PRECISION,
    "cap_rsrv" DOUBLE PRECISION,
    "specific_reserves" DOUBLE PRECISION,
    "surplus_rsrv" DOUBLE PRECISION,
    "prov_nom_risks" DOUBLE PRECISION,
    "undistributed_profit" DOUBLE PRECISION,
    "cnvd_diff_foreign_curr_stat" DOUBLE PRECISION,
    "tot_shrhldr_eqy_excl_min_int" DOUBLE PRECISION,
    "minority_int" DOUBLE PRECISION,
    "total_equity" DOUBLE PRECISION,
    "tot_liab_shrhldr_eqy" DOUBLE PRECISION,
    "cash_deposits_central_bank" DOUBLE PRECISION,
    "asset_dep_oth_banks_fin_inst" DOUBLE PRECISION,
    "precious_metals" DOUBLE PRECISION,
    "rcv_invest" DOUBLE PRECISION,
    "oth_assets" DOUBLE PRECISION,
    "liab_dep_oth_banks_fin_inst" DOUBLE PRECISION,
    "agency_bus_liab" DOUBLE PRECISION,
    "oth_liab" DOUBLE PRECISION,
    "unconfirmed_invest_loss" DOUBLE PRECISION,
    "tot_shrhldr_eqy_incl_min_int" DOUBLE PRECISION,
    "inventory_depreciation_reserve" DOUBLE PRECISION,
    "current_ratio" DOUBLE PRECISION,
    "total_equity_and_liabilities" DOUBLE PRECISION,
    "m_stateTypeCode" DOUBLE PRECISION,
    "m_source" DOUBLE PRECISION,
    "m_coverPeriod" DOUBLE PRECISION,
    "m_industryCode" DOUBLE PRECISION,
    "m_balanceCurrency" DOUBLE PRECISION,
    "m_cashAdepositsCentralBank" DOUBLE PRECISION,
    "m_nobleMetal" DOUBLE PRECISION,
    "m_depositsOtherFinancialInstitutions" DOUBLE PRECISION,
    "m_currentInvestment" DOUBLE PRECISION,
    "m_redemptoryMonetaryCapitalSale" DOUBLE PRECISION,
    "m_netAmountSubrogation" DOUBLE PRECISION,
    "m_refundableDeposits" DOUBLE PRECISION,
    "m_netAmountLoanPledged" DOUBLE PRECISION,
    "m_fixedTimeDeposit" DOUBLE PRECISION,
    "m_netLongtermDebtInvestments" DOUBLE PRECISION,
    "m_permanentInvestment" DOUBLE PRECISION,
    "m_depositForcapitalRecognizance" DOUBLE PRECISION,
    "m_netBalConstructionProgress" DOUBLE PRECISION,
    "m_separateAccountAssets" DOUBLE PRECISION,
    "m_capitalInvicariousBussiness" DOUBLE PRECISION,
    "m_otherAssets" DOUBLE PRECISION,
    "m_depositsWithBanksOtherFinancialIns" DOUBLE PRECISION,
    "m_indemnityPayable" DOUBLE PRECISION,
    "m_policyDividendPayable" DOUBLE PRECISION,
    "m_guaranteeInvestmentFunds" DOUBLE PRECISION,
    "m_premiumsReceivedAdvance" DOUBLE PRECISION,
    "m_insuranceLiabilities" DOUBLE PRECISION,
    "m_liabilitiesIndependentAccounts" DOUBLE PRECISION,
    "m_liabilitiesVicariousBusiness" DOUBLE PRECISION,
    "m_otherLiablities" DOUBLE PRECISION,
    "m_capitalPremium" DOUBLE PRECISION,
    "m_petainedProfit" DOUBLE PRECISION,
    "m_provisionTransactionRisk" DOUBLE PRECISION,
    "m_otherReserves" DOUBLE PRECISION,
    "stock_code" VARCHAR(20) NOT NULL,
    "report_date" DATE NOT NULL,
    "announce_date" DATE,
    PRIMARY KEY ("stock_code", "report_date", "announce_date")
);

-- Income → fin_income
CREATE TABLE IF NOT EXISTS "fin_income" (
    "revenue_inc" DOUBLE PRECISION,
    "earned_premium" DOUBLE PRECISION,
    "real_estate_sales_income" DOUBLE PRECISION,
    "total_operating_cost" DOUBLE PRECISION,
    "real_estate_sales_cost" DOUBLE PRECISION,
    "research_expenses" DOUBLE PRECISION,
    "surrender_value" DOUBLE PRECISION,
    "net_payments" DOUBLE PRECISION,
    "net_withdrawal_ins_con_res" DOUBLE PRECISION,
    "policy_dividend_expenses" DOUBLE PRECISION,
    "reinsurance_cost" DOUBLE PRECISION,
    "change_income_fair_value" DOUBLE PRECISION,
    "futures_loss" DOUBLE PRECISION,
    "trust_income" DOUBLE PRECISION,
    "subsidize_revenue" DOUBLE PRECISION,
    "other_business_profits" DOUBLE PRECISION,
    "net_profit_excl_merged_int_inc" DOUBLE PRECISION,
    "int_inc" DOUBLE PRECISION,
    "handling_chrg_comm_inc" DOUBLE PRECISION,
    "less_handling_chrg_comm_exp" DOUBLE PRECISION,
    "other_bus_cost" DOUBLE PRECISION,
    "plus_net_gain_fx_trans" DOUBLE PRECISION,
    "il_net_loss_disp_noncur_asset" DOUBLE PRECISION,
    "inc_tax" DOUBLE PRECISION,
    "unconfirmed_invest_loss" DOUBLE PRECISION,
    "net_profit_excl_min_int_inc" DOUBLE PRECISION,
    "less_int_exp" DOUBLE PRECISION,
    "other_bus_inc" DOUBLE PRECISION,
    "revenue" DOUBLE PRECISION,
    "total_expense" DOUBLE PRECISION,
    "less_taxes_surcharges_ops" DOUBLE PRECISION,
    "sale_expense" DOUBLE PRECISION,
    "less_gerl_admin_exp" DOUBLE PRECISION,
    "financial_expense" DOUBLE PRECISION,
    "less_impair_loss_assets" DOUBLE PRECISION,
    "plus_net_invest_inc" DOUBLE PRECISION,
    "incl_inc_invest_assoc_jv_entp" DOUBLE PRECISION,
    "oper_profit" DOUBLE PRECISION,
    "plus_non_oper_rev" DOUBLE PRECISION,
    "less_non_oper_exp" DOUBLE PRECISION,
    "tot_profit" DOUBLE PRECISION,
    "net_profit_incl_min_int_inc" DOUBLE PRECISION,
    "net_profit_incl_min_int_inc_after" DOUBLE PRECISION,
    "minority_int_inc" DOUBLE PRECISION,
    "s_fa_eps_basic" DOUBLE PRECISION,
    "s_fa_eps_diluted" DOUBLE PRECISION,
    "total_income" DOUBLE PRECISION,
    "total_income_minority" DOUBLE PRECISION,
    "other_compreh_inc" DOUBLE PRECISION,
    "m_stateTypeCode" DOUBLE PRECISION,
    "m_source" DOUBLE PRECISION,
    "m_coverPeriod" DOUBLE PRECISION,
    "m_industryCode" DOUBLE PRECISION,
    "m_currency" DOUBLE PRECISION,
    "m_netinterestIncome" DOUBLE PRECISION,
    "m_netFeesCommissions" DOUBLE PRECISION,
    "m_insuranceBusiness" DOUBLE PRECISION,
    "m_separatePremium" DOUBLE PRECISION,
    "m_asideReservesUndueLiabilities" DOUBLE PRECISION,
    "m_paymentsInsuranceClaims" DOUBLE PRECISION,
    "m_amortizedCompensationExpenses" DOUBLE PRECISION,
    "m_netReserveInsuranceLiability" DOUBLE PRECISION,
    "m_policyReserve" DOUBLE PRECISION,
    "m_amortizeInsuranceReserve" DOUBLE PRECISION,
    "m_nsuranceFeesCommissionExpenses" DOUBLE PRECISION,
    "m_operationAdministrativeExpense" DOUBLE PRECISION,
    "m_amortizedReinsuranceExpenditure" DOUBLE PRECISION,
    "m_netProfitLossdisposalNonassets" DOUBLE PRECISION,
    "m_otherItemsAffectingNetProfit" DOUBLE PRECISION,
    "net_int_inc" DOUBLE PRECISION,
    "net_handling_chrg_comm_inc" DOUBLE PRECISION,
    "net_inc_other_ops" DOUBLE PRECISION,
    "plus_net_gain_chg_fv" DOUBLE PRECISION,
    "plus_net_inc_other_bus" DOUBLE PRECISION,
    "oper_exp" DOUBLE PRECISION,
    "tot_compreh_inc" DOUBLE PRECISION,
    "tot_compreh_inc_min_shrhldr" DOUBLE PRECISION,
    "tot_compreh_inc_parent_comp" DOUBLE PRECISION,
    "actual_ann_dt" DOUBLE PRECISION,
    "operating_revenue" DOUBLE PRECISION,
    "cost_of_goods_sold" DOUBLE PRECISION,
    "stock_code" VARCHAR(20) NOT NULL,
    "report_date" DATE NOT NULL,
    "announce_date" DATE,
    PRIMARY KEY ("stock_code", "report_date", "announce_date")
);

-- CashFlow → fin_cashflow
CREATE TABLE IF NOT EXISTS "fin_cashflow" (
    "cash_received_ori_ins_contract_pre" DOUBLE PRECISION,
    "net_cash_received_rei_ope" DOUBLE PRECISION,
    "net_increase_insured_funds" DOUBLE PRECISION,
    "net_increase_in_disposal" DOUBLE PRECISION,
    "cash_for_interest" DOUBLE PRECISION,
    "net_increase_in_repurchase_funds" DOUBLE PRECISION,
    "cash_for_payment_original_insurance" DOUBLE PRECISION,
    "cash_payment_policy_dividends" DOUBLE PRECISION,
    "disposal_other_business_units" DOUBLE PRECISION,
    "cash_received_from_pledges" DOUBLE PRECISION,
    "cash_paid_for_investments" DOUBLE PRECISION,
    "net_increase_in_pledged_loans" DOUBLE PRECISION,
    "cash_paid_by_subsidiaries" DOUBLE PRECISION,
    "increase_in_cash_paid" DOUBLE PRECISION,
    "cass_received_sub_abs" DOUBLE PRECISION,
    "cass_received_sub_investments" DOUBLE PRECISION,
    "minority_shareholder_profit_loss" DOUBLE PRECISION,
    "unrecognized_investment_losses" DOUBLE PRECISION,
    "ncrease_deferred_income" DOUBLE PRECISION,
    "projected_liability" DOUBLE PRECISION,
    "increase_operational_payables" DOUBLE PRECISION,
    "reduction_outstanding_amounts_less" DOUBLE PRECISION,
    "reduction_outstanding_amounts_more" DOUBLE PRECISION,
    "goods_sale_and_service_render_cash" DOUBLE PRECISION,
    "net_incr_dep_cob" DOUBLE PRECISION,
    "net_incr_loans_central_bank" DOUBLE PRECISION,
    "net_incr_fund_borr_ofi" DOUBLE PRECISION,
    "tax_levy_refund" DOUBLE PRECISION,
    "cash_paid_invest" DOUBLE PRECISION,
    "other_cash_recp_ral_oper_act" DOUBLE PRECISION,
    "stot_cash_inflows_oper_act" DOUBLE PRECISION,
    "goods_and_services_cash_paid" DOUBLE PRECISION,
    "net_incr_clients_loan_adv" DOUBLE PRECISION,
    "net_incr_dep_cbob" DOUBLE PRECISION,
    "handling_chrg_paid" DOUBLE PRECISION,
    "cash_pay_beh_empl" DOUBLE PRECISION,
    "pay_all_typ_tax" DOUBLE PRECISION,
    "other_cash_pay_ral_oper_act" DOUBLE PRECISION,
    "stot_cash_outflows_oper_act" DOUBLE PRECISION,
    "net_cash_flows_oper_act" DOUBLE PRECISION,
    "cash_recp_disp_withdrwl_invest" DOUBLE PRECISION,
    "cash_recp_return_invest" DOUBLE PRECISION,
    "net_cash_recp_disp_fiolta" DOUBLE PRECISION,
    "other_cash_recp_ral_inv_act" DOUBLE PRECISION,
    "stot_cash_inflows_inv_act" DOUBLE PRECISION,
    "cash_pay_acq_const_fiolta" DOUBLE PRECISION,
    "stot_cash_outflows_inv_act" DOUBLE PRECISION,
    "net_cash_flows_inv_act" DOUBLE PRECISION,
    "cash_recp_cap_contrib" DOUBLE PRECISION,
    "cash_recp_borrow" DOUBLE PRECISION,
    "proc_issue_bonds" DOUBLE PRECISION,
    "other_cash_recp_ral_fnc_act" DOUBLE PRECISION,
    "stot_cash_inflows_fnc_act" DOUBLE PRECISION,
    "cash_prepay_amt_borr" DOUBLE PRECISION,
    "cash_pay_dist_dpcp_int_exp" DOUBLE PRECISION,
    "other_cash_pay_ral_fnc_act" DOUBLE PRECISION,
    "stot_cash_outflows_fnc_act" DOUBLE PRECISION,
    "net_cash_flows_fnc_act" DOUBLE PRECISION,
    "eff_fx_flu_cash" DOUBLE PRECISION,
    "net_incr_cash_cash_equ" DOUBLE PRECISION,
    "cash_cash_equ_beg_period" DOUBLE PRECISION,
    "cash_cash_equ_end_period" DOUBLE PRECISION,
    "net_profit" DOUBLE PRECISION,
    "plus_prov_depr_assets" DOUBLE PRECISION,
    "depr_fa_coga_dpba" DOUBLE PRECISION,
    "amort_intang_assets" DOUBLE PRECISION,
    "amort_lt_deferred_exp" DOUBLE PRECISION,
    "decr_deferred_exp" DOUBLE PRECISION,
    "incr_acc_exp" DOUBLE PRECISION,
    "loss_disp_fiolta" DOUBLE PRECISION,
    "loss_scr_fa" DOUBLE PRECISION,
    "loss_fv_chg" DOUBLE PRECISION,
    "fin_exp" DOUBLE PRECISION,
    "invest_loss" DOUBLE PRECISION,
    "decr_deferred_inc_tax_assets" DOUBLE PRECISION,
    "incr_deferred_inc_tax_liab" DOUBLE PRECISION,
    "decr_inventories" DOUBLE PRECISION,
    "decr_oper_payable" DOUBLE PRECISION,
    "others" DOUBLE PRECISION,
    "im_net_cash_flows_oper_act" DOUBLE PRECISION,
    "conv_debt_into_cap" DOUBLE PRECISION,
    "conv_corp_bonds_due_within_1y" DOUBLE PRECISION,
    "fa_fnc_leases" DOUBLE PRECISION,
    "end_bal_cash" DOUBLE PRECISION,
    "less_beg_bal_cash" DOUBLE PRECISION,
    "plus_end_bal_cash_equ" DOUBLE PRECISION,
    "less_beg_bal_cash_equ" DOUBLE PRECISION,
    "im_net_incr_cash_cash_equ" DOUBLE PRECISION,
    "net_incr_int_handling_chrg" DOUBLE PRECISION,
    "net_cash_deal_subcompany" DOUBLE PRECISION,
    "cash_from_mino_s_invest_sub" DOUBLE PRECISION,
    "fix_intan_other_asset_dispo_cash_payment" DOUBLE PRECISION,
    "other_cash_pay_ral_inv_act" DOUBLE PRECISION,
    "m_stateTypeCode" DOUBLE PRECISION,
    "m_source" DOUBLE PRECISION,
    "m_coverPeriod" DOUBLE PRECISION,
    "m_industryCode" DOUBLE PRECISION,
    "m_currency" DOUBLE PRECISION,
    "m_cashSellingProvidingServices" DOUBLE PRECISION,
    "m_netDecreaseUnwindingFunds" DOUBLE PRECISION,
    "m_netReductionPurchaseRebates" DOUBLE PRECISION,
    "m_netIncreaseDepositsBanks" DOUBLE PRECISION,
    "m_netCashReinsuranceBusiness" DOUBLE PRECISION,
    "m_netReductionDeposInveFunds" DOUBLE PRECISION,
    "m_netIncreaseUnwindingFunds" DOUBLE PRECISION,
    "m_netReductionAmountBorrowedFunds" DOUBLE PRECISION,
    "m_netReductionSaleRepurchaseProceeds" DOUBLE PRECISION,
    "m_investmentPaidInCash" DOUBLE PRECISION,
    "m_paymentOtherCashRelated" DOUBLE PRECISION,
    "m_cashOutFlowsInvesactivities" DOUBLE PRECISION,
    "m_absorbCashEquityInv" DOUBLE PRECISION,
    "m_otherImpactsOnCash" DOUBLE PRECISION,
    "m_addOperatingReceivableItems" DOUBLE PRECISION,
    "stock_code" VARCHAR(20) NOT NULL,
    "report_date" DATE NOT NULL,
    "announce_date" DATE,
    PRIMARY KEY ("stock_code", "report_date", "announce_date")
);

-- Pershareindex → fin_indicator
CREATE TABLE IF NOT EXISTS "fin_indicator" (
    "s_fa_ocfps" DOUBLE PRECISION,
    "s_fa_bps" DOUBLE PRECISION,
    "s_fa_eps_basic" DOUBLE PRECISION,
    "s_fa_eps_diluted" DOUBLE PRECISION,
    "s_fa_undistributedps" DOUBLE PRECISION,
    "s_fa_surpluscapitalps" DOUBLE PRECISION,
    "adjusted_earnings_per_share" DOUBLE PRECISION,
    "du_return_on_equity" DOUBLE PRECISION,
    "sales_gross_profit" DOUBLE PRECISION,
    "inc_revenue_rate" DOUBLE PRECISION,
    "du_profit_rate" DOUBLE PRECISION,
    "inc_net_profit_rate" DOUBLE PRECISION,
    "adjusted_net_profit_rate" DOUBLE PRECISION,
    "inc_total_revenue_annual" DOUBLE PRECISION,
    "inc_net_profit_to_shareholders_annual" DOUBLE PRECISION,
    "adjusted_profit_to_profit_annual" DOUBLE PRECISION,
    "equity_roe" DOUBLE PRECISION,
    "net_roe" DOUBLE PRECISION,
    "total_roe" DOUBLE PRECISION,
    "gross_profit" DOUBLE PRECISION,
    "net_profit" DOUBLE PRECISION,
    "actual_tax_rate" DOUBLE PRECISION,
    "pre_pay_operate_income" DOUBLE PRECISION,
    "sales_cash_flow" DOUBLE PRECISION,
    "gear_ratio" DOUBLE PRECISION,
    "inventory_turnover" DOUBLE PRECISION,
    "s_fa_fcfeps" DOUBLE PRECISION,
    "s_fa_retainedps" DOUBLE PRECISION,
    "s_fa_fcffps" DOUBLE PRECISION,
    "s_fa_ebitps" DOUBLE PRECISION,
    "s_fa_cfps" DOUBLE PRECISION,
    "s_fa_grps" DOUBLE PRECISION,
    "s_fa_surplusreserveps" DOUBLE PRECISION,
    "s_fa_orps" DOUBLE PRECISION,
    "inc_revenue" DOUBLE PRECISION,
    "inc_gross_profit" DOUBLE PRECISION,
    "inc_profit_before_tax" DOUBLE PRECISION,
    "du_profit" DOUBLE PRECISION,
    "inc_net_profit" DOUBLE PRECISION,
    "adjusted_net_profit" DOUBLE PRECISION,
    "stock_code" VARCHAR(20) NOT NULL,
    "report_date" DATE NOT NULL,
    "announce_date" DATE,
    PRIMARY KEY ("stock_code", "report_date", "announce_date")
);

-- Capital → fin_capital
CREATE TABLE IF NOT EXISTS "fin_capital" (
    "total_capital" DOUBLE PRECISION,
    "circulating_capital" DOUBLE PRECISION,
    "restrict_circulating_capital" DOUBLE PRECISION,
    "freeFloatCapital" DOUBLE PRECISION,
    "stock_code" VARCHAR(20) NOT NULL,
    "report_date" DATE NOT NULL,
    "announce_date" DATE,
    PRIMARY KEY ("stock_code", "report_date")
);

-- Holdernum → fin_holdernum
CREATE TABLE IF NOT EXISTS "fin_holdernum" (
    "shareholder" DOUBLE PRECISION,
    "shareholderA" DOUBLE PRECISION,
    "shareholderB" DOUBLE PRECISION,
    "shareholderH" DOUBLE PRECISION,
    "shareholderFloat" DOUBLE PRECISION,
    "shareholderOther" DOUBLE PRECISION,
    "stock_code" VARCHAR(20) NOT NULL,
    "announce_date" DATE,
    "end_date" DATE NOT NULL,
    PRIMARY KEY ("stock_code", "end_date")
);

-- Top10holder → fin_top10_holder
CREATE TABLE IF NOT EXISTS "fin_top10_holder" (
    "quantity" DOUBLE PRECISION,
    "ratio" DOUBLE PRECISION,
    "rank" SMALLINT NOT NULL,
    "name" TEXT,
    "type" TEXT,
    "reason" TEXT,
    "nature" TEXT,
    "stock_code" VARCHAR(20) NOT NULL,
    "announce_date" DATE,
    "end_date" DATE NOT NULL,
    PRIMARY KEY ("stock_code", "end_date", "rank")
);

-- Top10flowholder → fin_top10_flow_holder
CREATE TABLE IF NOT EXISTS "fin_top10_flow_holder" (
    "quantity" DOUBLE PRECISION,
    "ratio" DOUBLE PRECISION,
    "rank" SMALLINT NOT NULL,
    "name" TEXT,
    "type" TEXT,
    "reason" TEXT,
    "nature" TEXT,
    "stock_code" VARCHAR(20) NOT NULL,
    "announce_date" DATE,
    "end_date" DATE NOT NULL,
    PRIMARY KEY ("stock_code", "end_date", "rank")
);
